---
title: "p8105_hw5_ay2452"
author: "Alicia Yang"
date: "11/11/2019"
output: github_document
---

```{r setup}
library(tidyverse)
library(viridis)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r Problem 1}
iris_function = function(x) {
  if (is.numeric(x)) {
   replace_na(x, mean(x, na.rm = TRUE))
  }
  else if (is.character(x)) {
    replace_na(x, "virginia")
  }
}

output = vector("list", length = 5)

for (i in 1:5) {
  output[[i]] = iris_function(iris_with_missing[[i]])
}

output = map(iris_with_missing, iris_function)
```

```{r Problem 2}
Study_df = list.files(path = "./data",
             pattern = "*.csv", 
             full.names = TRUE) %>%
  map_dfr(read_csv, .id = "subject_id") %>%
  janitor::clean_names() %>%
  mutate(
    group = as.character(subject_id),
    group = recode(group, "1" = "control", "2" = "control", "3" = "control", "4" = "control", "5" = "control", "6" = "control", "7" = "control", "8" = "control", "9" = "control", "10" = "control", "11" = "experiment", "12" = "experiment", "13" = "experiment", "14" = "experiment", "15" = "experiment", "16" = "experiment", "17" = "experiment", "18" = "experiment", "19" = "experiment", "20" = "experiment" )) %>% 
  pivot_longer(
    week_1: week_8,
    names_to = "time", 
    values_to = "observations"
  )

Study_df %>% 
  ggplot(aes(x = time, y = observations, group = group, color = group)) + 
  geom_path() +
  labs(title = "Observation of each subject over time") + 
  viridis::scale_color_viridis(
    discrete = TRUE)
##Over time, it appears that the general trend of number of observations increases for individuals in the experimental group. Individuals in the control group seem to start and end at around the same observation number. 
```

```{r Problem 3}
sim_regression = function(beta1) {
  
  sim_data = tibble(
    
    n = 30,
    x_i1 = rnorm(n, mean = 1, sd = 1),
    beta0 = 2, 
    sigma2 = 50,
    y = beta0+beta1 * x_i1 + rnorm(n, 0, sigma2)
  )
  
  ls_fit = lm(y ~ x_i1, data = sim_data)
  
  ls_fit %>% 
  broom::tidy() %>%
  filter(term == x_i1) %>%
  select(estimate, p.value)
}
```
